config/routes.rb
Silvergum::Application.routes.draw do
  devise_for :customers

  root 'home#index'

  namespace :my do
    resource :account
    resources :credentials
  end
end

app/models/credential.rb
class Credential < ActiveRecord::Base
  belongs_to :customer
  belongs_to :provider

  validates :customer,          presence: true
  validates :provider,          presence: true
  validates :access_key_id,     presence: true
  validates :secret_access_key, presence: true

  delegate :name, to: :provider, prefix: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
    :trackable, :validatable, :confirmable

  has_many :credentials, dependent: :destroy
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #
end

app/controllers/my/accounts_controller.rb
class My::AccountsController < My::ApplicationController
  #
end

app/controllers/my/application_controller.rb
class My::ApplicationController < ApplicationController
  before_filter :authenticate_customer!
end

app/controllers/my/credentials_controller.rb
class My::CredentialsController < My::ApplicationController
  expose(:credential) { current_customer.credentials.build credential_params }

  def create
    if credential.save
      redirect_to [:my, :account]
    else
      render 'new'
    end
  end

  private

  def credential_params
    return {} if params[:credential].nil?

    params.require(:credential).permit(
      :provider_id, :access_key_id, :secret_access_key
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<p>Be responsible about the power your servers use - offset the carbon emissions automatically.</p>

<h2>You:</h2>

<ul>
  <li>Sign up for an account.</li>
  <li>Provide your AWS and/or Rackspace API details.</li>
  <li>Provide your credit card details.</li>
</ul>

<h2>We:</h2>

<ul>
  <li>Charge you each month based on the carbon emissions your servers have generated.</li>
  <li>Buy carbon emissions in bulk to cover all customers' emissions.</li>
</ul>

<p>Carbon emissions are calculated through open-sourced formulas from <a href="http://impact.brighterplanet.com/models">Brighter Planet</a> and purchased through <a href=""></a>, and we'll charge an extra 10% to cover our own costs. There's nothing more to it.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutoOffset.Me</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => false %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>Automatic Carbon Offsets</h1>

    <%- if customer_signed_in? -%>
      <p>Welcome <%= current_customer.email %></p>
      <p><%= link_to 'Sign out', destroy_customer_session_path, method: :destroy %></p>
    <%- else -%>
      <p><%= link_to 'Sign up', new_customer_registration_path %></p>
    <%- end -%>
  </header>

  <p class="notice"><%= notice %></p>
  <p class="notice"><%= alert  %></p>

  <%= yield %>

  <footer>
    <p><a href="https://autooffset.me">AutoOffset.Me</a> is brought to you by <a href="http://freelancing-gods.com">Pat Allan</a>.</p>
    <p>Copyright &copy; 2013, and <a href="https://github.com/autooffset">all code</a> is released under an open MIT License.
  </footer>
</body>
</html>

app/views/my/accounts/show.html.erb
<h2>My Account</h2>

<h3>My Credentials</h3>

<ul>
  <% current_customer.credentials.each do |credential| %>
  <li><%= credential.provider_name %> <%= credential.access_key_id %></li>
  <% end %>
</ul>

<%= link_to 'Add Credentials', [:new, :my, :credential] %>

app/views/my/credentials/new.html.erb
<%= semantic_form_for [:my, credential] do |form| %>
  <%= form.inputs do %>
    <%= form.input :provider %>
    <%= form.input :access_key_id %>
    <%= form.input :secret_access_key %>
  <% end %>
  <%= form.actions do %>
    <%= form.action :submit %>
  <% end %>
<% end %>